# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170730_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='standardpage',
            name='frameurl',
            field=models.CharField(blank=True, default='blank', max_length=100),
        ),
    ]
