# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('user_activty', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PackageThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagethreshold_text', models.CharField(max_length=100)),
                ('threshold_rrc', models.FloatField()),
                ('threshold_prb_utilization', models.FloatField()),
                ('threshold_upoct', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SceneAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('scene', models.CharField(max_length=100)),
                ('guaranteed_bandwidth', models.FloatField()),
                ('rrc_growth_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='Quick Task', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='sceneattribute',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_scene', to='capfore.Task'),
        ),
        migrations.AddField(
            model_name='packagethreshold',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_package', to='capfore.Task'),
        ),
        migrations.AddField(
            model_name='cityattribute',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_city', to='capfore.Task'),
        ),
    ]
