# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capfore', '0007_auto_20170802_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DOING', 'DOING'), ('DONE', 'DONE')], default='python', max_length=100),
        ),
    ]
