# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capfore', '0008_auto_20170802_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='foredate',
            field=models.DateField(default=datetime.date(2017, 11, 1), verbose_name='预测时间点'),
        ),
        migrations.AlterField(
            model_name='cityattribute',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citys', to='capfore.Task'),
        ),
        migrations.AlterField(
            model_name='packagethreshold',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='capfore.Task'),
        ),
        migrations.AlterField(
            model_name='sceneattribute',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='capfore.Task'),
        ),
    ]
