# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capfore', '0009_auto_20170803_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgi', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskcell', to='capfore.Task')),
            ],
        ),
    ]
