# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capfore', '0010_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='band',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='erab_nbrmeanestab',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='erab_nbrsuccestab',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='erab_upoctdl',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='f',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='indoor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='isneededexpansion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='long',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='packagetype',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctdl',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctdl_e',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctdl_factorlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctdl_forelist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctdl_nowlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctdl_old',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctdl_oldlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctdl_predict',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctul',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctul_e',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctul_factorlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctul_forelist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctul_nowlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctul_old',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctul_oldlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='pdcp_upoctul_predict',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_dlutilization',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_dlutilization_e',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_dlutilization_factorlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_dlutilization_forelist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_dlutilization_nowlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_dlutilization_old',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_dlutilization_oldlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_dlutilization_predict',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_ulutilization',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_ulutilization_e',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_ulutilization_factorlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_ulutilization_forelist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_ulutilization_nowlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_ulutilization_old',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_ulutilization_oldlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='prb_ulutilization_predict',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_connmean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_connmean_e',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_connmean_factorlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_connmean_forelist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_connmean_nowlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_connmean_old',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_connmean_oldlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_connmean_predict',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_effectiveconnmean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_effectiveconnmean_e',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_effectiveconnmean_factorlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_effectiveconnmean_forelist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_effectiveconnmean_nowlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_effectiveconnmean_old',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_effectiveconnmean_oldlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='rrc_effectiveconnmean_predict',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='scene1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='scene2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cell',
            name='scene3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='capfore.Task'),
        ),
    ]
